on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  process_recipe:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - id: changed-files
        name: get changed files
        uses: jitterbit/get-changed-files@v1

      - name: list changed files
        run: |
          for changed_file in ${{ steps.changed-files.outputs.all }}; do
            echo "This PR changed: ${changed_file}."
          done

      - name: decide if meta.yml in pr
        id: meta
        run: |
          for changed_file in ${{ steps.changed-files.outputs.all }}; do
            if [[ ${changed_file} =~ ^.*recipes\/.*meta.yml$ ]];
            then
              echo "::set-output name=META_YAML::${changed_file}";
              break
            fi
          done

      - name: process_recipe
        if: ${{ steps.meta.outputs.META_YAML != null }}
        uses: ./.github/actions/local_action
        with:
          path_to_meta_yml: ${{ steps.meta.outputs.META_YAML }}
