on: [push, workflow_dispatch]

jobs:
  process_recipe:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: process_recipe
        uses: ciaranevans/docker-github-action-test@main
        with:
          path_to_meta_yml: "folder_1/folder_2/a_test_meta.yml"
